[tools]
awscli = { version = "latest", symlink_bins = "true" }
flux2 = "latest"
fzf = "latest"
go = "1.26.3"
kubecolor = "latest"
kubectl = "latest"
kubectx = "latest"
kubens = "latest"
lsd = "latest"
opensearch-cli = "latest"
ripgrep = "latest"
starship = "latest"
teleport-ent = "latest"
terraform = "1.9.8"
terragrunt = "0.99.1"
yq = "latest"
zellij = "latest"
